spring:
  application:
    name: spring-cloud-nacos-producer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.14:8848
  profiles:
    active: producer1

---
spring:
  profiles: producer1
server:
  port: 9000

---
spring:
  profiles: producer2
server:
  port: 9001
