spring:
  application:
    name: spring-cloud-nacos-producer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: producer1
  boot:
    admin:
      client:
        url: http://localhost:8020
        instance:
          prefer-ip: true
          service-url: http://192.168.1.23:9000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
---
spring:
  profiles: producer1
server:
  port: 9000

---
spring:
  profiles: producer2
server:
  port: 9001
