server:
  port: 8080
spring:
  application:
    name: spring-cloud-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.14:8848
management:
  endpoint:
    nacos-config:
      enabled: true
  endpoints:
    web:
      exposure:
        include: nacos-config
