spring:
  application:
    name: alibaba-dubbo-client
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8002

dubbo:
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: alibaba-dubbo-server