logging:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: ai.guiji.seata.storage.entity
server:
  port: 8182
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://172.16.1.109:3306/db_storage
    username: root
management:
  endpoints:
    web:
      cors:
        allowed-methods: '*'
