spring:
  application:
    name: alibaba-dubbo-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8001

  # 指定 Dubbo 服务实现类的扫描基准包
dubbo:
  scan:
    base-packages: ai.guiji.dubbo.server
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost